### PR TITLE
Allow for a specific instance of SpiceMainConn in sendCtrlAltDel

### PR DESCRIPTION
**Pull request by bmclaughlin**

### CODE REVIEW

**Comment by himdel** [comment]
@bmclaughlin This would break the code for SUI which does use the spice_auto template.

Can you make it so that the global object is used when the parameter is not provided?

**Comment by bmclaughlin** [comment]
@himdel, Should be much better now.

**Comment by himdel** [comment]
LGTM, merged, will still need to release the new version of this...

Will release 1.7.* first, and if it turns out we need 1.6.* as well...

**Comment by himdel** [comment]
Released in spice-html5-bower 1.7.2 (both bower & npm)

**Pull request merged**
